name: Validate Catalog
description: Validates OPM Catalog
inputs:
  file:
    description: Path to veneer yaml to render
    required: true
outputs:
  renderfile:
    description: Rendered JSON
runs:
  using: docker
  image: docker://ghcr.io/machine-node-linker/opm-actions:v1
  args:
    - alpha
    - render-template
    - semver
    - ${{inputs.file}}
    - renderfile
  env:
    out_file: ${RENDER_TEMP}/rendered-semver.json
