name: Validate Catalog
description: Validates OPM Catalog
inputs:
  file:
    description: Path to veneer yaml to render
    required: true
outputs:
  rendered:
    description: Rendered JSON
runs:
  using: docker
  image: docker://ghcr.io/machine-node-linker/opm-actions:v1
  args:
    - alpha
    - render-veneer
    - semver
    - ${{inputs.file}}
    - rendered
  env:
    out_file: process.env['RUNNER_TEMP']/rendered-semver.json
