name: Validate Catalog
description: Validates OPM Catalog
inputs:
  render:
    description: Rendered Catalog JSON
    required: true
  package:
    description: Package JSON
    required: true
outputs:
  combined:
    description: Combined JSON String
    value: ${{steps.last.outputs.value}}

runs:
  using: composite
  steps:
    - uses: edwardgeorge/jq-action@main
      if: ${{inputs.package != ''}}
      id: jq-package-icon
      with:
        input: ${{inputs.render}}
        script: 'if .schema == "olm.package" then {''icon'': ${{toJSON(fromJSON(inputs.package).icon)}}} + . else . end'
        compact: true

    - uses: edwardgeorge/jq-action@main
      if: ${{inputs.package != ''}}
      id: jq-package-description
      with:
        input: ${{steps.jq-package-icon.outputs.value}}
        script: 'if .schema == "olm.package" then {''description'': ${{fromJSON(inputs.package).description}}} else . end'
        compact: true

    - id: last
      shell: bash
      run: |
        if [ "${{steps.jq_package_description.outcome}}" == "skipped" ]; then
          echo "::set-output name=value::${{inputs.render}}"
        else
          echo "::set-output name=value::${{steps.jq-package-description.outputs.value}}"
        fi
