name: Validate Catalog
description: Validates OPM Catalog
inputs:
  catalog:
    description: Catalog Directory Path
    required: false
    default: catalog
outputs:
  error:
    description: Will be emtpy unless there is an error
runs:
  using: docker
  image: docker://ghcr.io/machine-node-linker/opm-actions:v2
  args:
    - validate
    - ${{inputs.catalog}}
    - error
