name: Validate Catalog
description: Validates OPM Catalog
inputs:
  catalog:
    description: Catalog Directory Path
    required: false
    default: catalog
runs: 
  using: docker
  image: docer://ghcr.io/machine-node-linker/opm-actions/opm:v1
  args:
    - validate
    - ${{inputs.catalog}}