name: create-veneer
description: Create OPM semver veneer if one doesnt exist
inputs:
  catalog:
    description: "Path to catalog (releative to workspace)"
    required: false
    default: catalog
  operator:
    description: Name of operator
    required: true
runs:
  using: docker
  image: docker://grc.io/machine-node-linker/manage-veneer:v0.1
  args:
    - create
    - --file
    - ${{inputs.catalog}}/${{inputs.operator}}/${{inputs.operator}}.semvar-veneer.yaml
