name: Make Package File
description: Creates OPM Package File
inputs:
  operator:
    description: Operator Name
    required: true
  description:
    description: Path to Operator Description File
    required: false
    default: ${{github.workspace}}/README.md
  icon:
    description: Path to Icon
    required: false
    default: ${{github.workspace}}/icon.png
  channel:
    description: Default Channel
    required: false
    default: stable
outputs:
  package:
    description: JSON Package Data
runs: 
  using: docker
  image: docker://ghcr.io/machine-node-linker/opm-actions/opm-actions:v1
  args:
    - init
    - ${{inputs.operator}}
    - --default-channel=${{inputs.channel}}
    - --description=${{inputs.description}}
    - --icon=${{inputs.icon}}
    - --output=json
    - package
