name: Write OPM Render Files
description: Write OPM Render Files
inputs:
  renderpath:
    description: Path to Rendered Catalog JSON (newline separated)
    required: true
  directory:
    description: path to write render files
    required: true
  icon:
    description: base64 encoded data for icon file
    required: false
  description:
    description: base64 encoded data for description data
    required: false

runs:
  using: composite
  steps:
    - shell: bash
      run: ${{github.action_path}}/script.sh
      env:
        RENDERPATH: ${{inputs.renderpath}}
        DIR: ${{inputs.directory}}
        ICON: ${{inputs.icon}}
        DESC: ${{inputs.description}}
