name: Build action image

on:
  push:
    paths:
      - ".src/*"
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Semantic Version
        id: version
        uses: PaulHatch/semantic-version@v4.0.3
        with:
          namespace: image
          major_pattern: "(Image MAJOR)"
          minor_pattern: "(Image MINOR)"
          format: "${major}.${minor}"
          change_path: ".src/Dockerfile .src/entrypoint.sh"

      - name: Tag Release
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "${{ steps.version.outputs.version_tag }}"
        continue-on-error: true

      - name: Build image
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            .src/Dockerfile
          context: .src/
          oci: true
          image: opm-actions
          tags: |
            latest
            v${{steps.version.outputs.major}} 
            v${{steps.version.outputs.major}}.${{steps.version.outputs.minor}}
          labels: |
            org.opencontainers.image.url="${{github.server_url}}/${{github.repository}}
            org.opencontainers.image.author="${{github.server_url}}/${{github.repository_owner}}
            org.opencontainers.image.created=${{github.event.head_commit.timestamp}}
            org.opencontainers.image.title={{opm-actions}}
            org.opencontainers.image.revision=${{github.sha}}
            org.opencontainers.image.version=${{steps.version.outputs.version_tag}}

      - name: Push image
        id: push
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build.outputs.image }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: ${{ steps.build.outputs.tags }}
