name: Test Custom Actions

on:
  push:
    branches:
      - "main"
    paths:
      - make-package
      - render-bundle
      - validate    
  pull_request:
    branches:
      - main
    paths:
      - make-package
      - render-bundle
      - validate    
  workflow_run:
    workflows:
      - Build action image
    types:
      - completed

jobs:
  test-make-package:
    name: Test make-package action
    runs-on: ubuntu-latest
    env:
      operator: test-operator
      channel: stable 
    steps:
      - name: Make Package
        id: make
        uses: machine-node-linker/opm-actions/make-package@v1
        with:
          operator: ${{env.operator}}
          channel: ${{env.channel}}
      - name: validate
        env: ${{fromJSON(steps.make.outputs.package)}}
        run: |
          set -e
          test ${{env.schema}} == "olm.package"
          test ${{env.name}} == ${{env.operator}}
          test ${{env.defaultChannel}} == ${{env.channel}}
  test-render-veneer-semver:
    name: Test render-veneer-semver
    runs-on: ubuntu-latest
    steps:
      - name: Render
        id: render
        uses: machine-node-linker/opm-actions/render-veneer-semver@v1
        with:
          file: render-veneer-semver/test/test.veneer-semver.yaml
      - name: confirm output
        run: |
          set -e
          test ${{steps.render.outputs.rendered}} != ""