name: Test Custom Actions

on:
  push:
    branches:
      - "main"
    paths:
      - make-package
      - render-bundle
      - validate    
  pull_request:
    branches:
      - main
    paths:
      - make-package
      - render-bundle
      - validate    
  workflow_run:
    workflows:
      - Build action image
    types:
      - completed

jobs:
  tests:
    name: Test make-package action
    runs-on: ubuntu-latest
    env:
      operator: test-operator
      channel: stable 
    steps:
      - name: Make Package
        id: make
        uses: machine-node-linker/opm-actions/make-package@v1
        with:
          operator: ${{env.operator}}
          channel: ${{env.channel}}
      - name: validate
        env: ${{fromJSON(steps.make.outputs.package)}}
        run: |
          test ${{env.schema}} == "olm.package"
          test ${{env.name}} == ${{env.operator}}
          test ${{env.defaultChannel}} == ${{env.channel}}