name: Test Custom Actions

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".src/*"
      - ".github/workflows/image-release.yaml"
      - ".gitignore"
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".src/*"
      - ".github/workflows/image-release.yaml"
      - ".gitignore"
  workflow_run:
    workflows:
      - Build action image
    types:
      - completed

jobs:
  test-render-veneer-semver:
    name: Test render-veneer-semver
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Render
        id: render
        uses: machine-node-linker/opm-actions/render-veneer-semver@v2
        with:
          file: render-veneer-semver/test/test.veneer-semver.yaml
      - name: confirm output
        run: |
          set -e
          test "${{steps.render.outputs.renderfile}}" != ""

  test-write-render-files:
    name: Test write-render-files
    runs-on: ubunutu-latest
    steps:
      - uses: actions/checkout@v3
      - name: write-files
        id: write
        uses: machine-node-linker/opm-actions/write-render-files@v2
        with:
          renderfile: write-render-files/test/rendered.json
          directory: ${{runner.temp}}
      - name: confirm output
        run: |
          set -e
          test -f "${{runner.temp}}/package.json"
          test -f "${{runner.temp}}/bundle.json"
          test -f "${{runner.temp}}/channel.json"
